-- Business Question 2

-- How has customer usage changed over time?

SELECT CUSTOMER_ID,MIN(LOGINS) KEEP (DENSE_RANK FIRST ORDER BY ACTIVITY_MONTH) AS START_LOGINS,MAX(LOGINS) KEEP (DENSE_RANK LAST ORDER BY ACTIVITY_MONTH) AS END_LOGINS,ROUND((MAX(LOGINS) KEEP (DENSE_RANK LAST ORDER BY ACTIVITY_MONTH)-MIN(LOGINS) KEEP (DENSE_RANK FIRST ORDER BY ACTIVITY_MONTH))/MIN(LOGINS) KEEP (DENSE_RANK FIRST ORDER BY ACTIVITY_MONTH)*100,2) AS USAGE_CHANGE_PCT
FROM DP_USAGE_ACTIVITY
GROUP BY CUSTOMER_ID
ORDER BY USAGE_CHANGE_PCT desc;

CUSTOMER_I START_LOGINS END_LOGINS USAGE_CHANGE_PCT
---------- ------------ ---------- ----------------
C004                  7         35              400
C001                 18         43           138.89
C003                 30         32             6.67
C005                 62         49           -20.97
C002                 48         23           -52.08